### ISSUE TITLE
[scrollview] Bug when rendering buffer with area > 65536

### ISSUE THREAD

**Issue by kxxt** [joshka/tui-widgets#33]
`Rect::new` clipped the rect if the area is larger than 65536, causing the buffer created in `ScrollView::new()` to be smaller than the `size` argument. However, it is possible to construct a `Rect` with area > 65536 directly. This could lead to panic when actually rendering widgets in the scrollview, like https://github.com/ratatui/ratatui/issues/1375

**Comment by joshka** [comment]
This should be fixed in the next release of Ratatui coming out this week.

**Comment by kxxt** [comment]
Should be fixed with `tui-scrollview = "0.5.0"`
