### ISSUE TITLE
Pull in scrollview PR from tui-scrollview

### ISSUE THREAD

**Issue by joshka** [joshka/tui-widgets#8]
https://github.com/joshka/tui-scrollview/pull/29

by @s9tpepper

**Comment by lucas-labs** [comment]
Hi there 😊! 
Is there anything preventing this from being merged? It would be a great addition.

**Comment by joshka** [comment]
Nothing other than time. Would you like to redo the PR making the required changes to make the change work with the tui-widgets monorepo? Ideally keep the commit author as the original author to credit their work on this.

**Comment by joshka** [comment]
done in #37
